.\" '\" t
.\" ** The above line should force tbl to be a preprocessor **
.\" Man page for fuse-zip
.TH "vmas-fs" "1" "July 2021" "FUSE filesystem to read and modify VPL archives" "FUSE filesystem to read and modify VPL archives"
.SH "NAME"
fuse\-zip \- a FUSE filesystem for vpl archives with write support
.SH "SYNOPSIS"
.\" The general command line
.B vmas\-fs
.RI [\| options \|]
zip\-file
mount\-point
.SH "OPTIONS"
.TP
\fB-h\fP
print help
.TP
\fB-V\fP
print version
.TP
\fB-r\fP
open archive in read\-only mode
.TP
\fB-o opt[,opt...]\fP
mount options
.TP
\fB-f\fP
don't detach from terminal
.TP
\fB-d\fP
turn on debugging, also implies \-f
.PP
If you want to specify character set conversion for file names in archive,
use the following fusermount options:

  \-omodules=iconv,from_code=$charset1,to_code=$charset2

See FUSE documentation for details.
.SH "DESCRIPTION"
.B vmas\-fs
is a fuse filesystem, that enables any program to work with a VPL archive as though it is a plain directory.
Unlike KIO or Gnome VFS, it can be used in any application without modifications.

Support for UNIX file permissions and owner information has been added in
version 0.4. See
.B PERMISSIONS
for details.
.SH "USAGE"
General usage would look like this

.TS
tab (@);
l l.
1@mkdir\ /tmp/zipArchive
2@fuse\-zip foobar.zip /tmp/zipArchive
3@(do something with the mounted file system)
4@fusermount \-u /tmp/zipArchive
.TE
.PP
Be patient. Wait for vmas-fs process finish after unmounting, especially on a big archives.
.SH "PERMISSIONS"
Access check will not be performed unless
\fB-o default_permissions\fP mount option is given.
.SH "FILES"
.TP 
.if !'po4a'hide' .I /var/log/user.log
see this file in case any errors occur
.SH "SEE ALSO"
.BR fusermount (1).
.SH "LICENSE"
.
You are not allowed to used it anywhere except within our products. Copyright protected.
.
.SH "AUTHORS"
.
V Publicidad SpA http://www.vmaspublicidad.com/~al
.br 
.
